// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Xuesheng.proto

package cz.yb.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cz.yb.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
