// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Xuesheng.proto

package cz.yb.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cz.yb.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cz.yb.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<cz.yb.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .cz.yb.proto.StudentResponse studentResponse = 1;</code>
   */
  cz.yb.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .cz.yb.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .cz.yb.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends cz.yb.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .cz.yb.proto.StudentResponse studentResponse = 1;</code>
   */
  cz.yb.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
