// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Xuesheng.proto

package cz.yb.proto;

public final class Xuesheng {
  private Xuesheng() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_yb_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cz_yb_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_yb_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cz_yb_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_yb_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cz_yb_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_yb_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cz_yb_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_yb_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cz_yb_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_yb_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cz_yb_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cz_yb_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cz_yb_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Xuesheng.proto\022\013cz.yb.proto\"\035\n\tMyReque" +
      "st\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010re" +
      "alname\030\002 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 " +
      "\001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003" +
      "age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"L\n\023StudentRespon" +
      "seList\0225\n\017studentResponse\030\001 \003(\0132\034.cz.yb." +
      "proto.StudentResponse\"%\n\rStreamRequest\022\024" +
      "\n\014request_info\030\001 \001(\t\"\'\n\016StreamResponse\022\025" +
      "\n\rresponse_info\030\001 \001(\t2\330\002\n\017XueshengServic" +
      "e\022J\n\025GetRealNameByUsername\022\026.cz.yb.proto" +
      ".MyRequest\032\027.cz.yb.proto.MyResponse\"\000\022Q\n" +
      "\020GetStudentsByAge\022\033.cz.yb.proto.StudentR" +
      "equest\032\034.cz.yb.proto.StudentResponse\"\0000\001" +
      "\022]\n\030GetStudentsWrapperByAges\022\033.cz.yb.pro" +
      "to.StudentRequest\032 .cz.yb.proto.StudentR" +
      "esponseList\"\000(\001\022G\n\006biTalk\022\032.cz.yb.proto." +
      "StreamRequest\032\033.cz.yb.proto.StreamRespon" +
      "se\"\000(\0010\001B\031\n\013cz.yb.protoB\010XueshengP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cz_yb_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cz_yb_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cz_yb_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_cz_yb_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cz_yb_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cz_yb_proto_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_cz_yb_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cz_yb_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cz_yb_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_cz_yb_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cz_yb_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cz_yb_proto_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_cz_yb_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cz_yb_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cz_yb_proto_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_cz_yb_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cz_yb_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cz_yb_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_cz_yb_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cz_yb_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cz_yb_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
